### ISSUE TITLE
Chart url

### ISSUE THREAD

**Issue by adriancampos** [ARCA-Industries/mud#36]
@asteffen I made a drop-in replacement for quickchart.io that has our branding, download button, etc. on the page. It's added to the [site ](https://github.com/ARCA-Industries/mud-site) repository. Use it exactly the same way you'd use quickchart; it passes its parameters straight through.

https://arcamud.web.app/chart/

Example: https://arcamud.web.app/chart/?c={type:%27bar%27,data:{labels:[%27January%27,%27February%27,%27March%27,%27April%27,%20%27May%27],%20datasets:[{label:%27Dogs%27,data:[50,60,70,180,190]},{label:%27Cats%27,data:[100,200,300,400,20]}]}}

If you can, it'd be cool to use it instead of quickchart.io just so we have control over the links our users share.

**Comment by adriancampos** [comment]
Also if we want to play around with it, we could create and share [firebase dynamic links](https://firebase.google.com/docs/dynamic-links/use-cases/user-to-user#add-share-buttons-that-send-dynamic-links) so that users receive a shortened url that redirects to the chart. That gives us
* much shorter (and professional looking) links
* somewhat blocks users from editing their data (if that matters)

Definitely not necessary but something else we could do.

**Comment by asteffen** [comment]
@adriancampos I changed plans and ended up not using quickchart.io to share charts. Instead of sharing a link, the user shares the chart image as a png file.
